# Generated by Django 5.0.3 on 2024-04-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='trimlevel',
            field=models.CharField(max_length=255),
        ),
    ]
